// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfig {
    "folders": FolderConfig[];

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField0_0($$parsedSource["folders"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class FolderConfig {
    "path": string;
    "scanMode": ScanMode;

    /** Creates a new FolderConfig instance. */
    constructor($$source: Partial<FolderConfig> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("scanMode" in $$source)) {
            this["scanMode"] = ScanMode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderConfig($$parsedSource as Partial<FolderConfig>);
    }
}

export enum ScanMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ScanModeNormal = "normal",
    ScanModeWalk = "walk",
};

// Private type creation functions
const $$createType0 = FolderConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
