// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfig {
    "folders": FolderConfig[];
    "tabs": TabConfig[];
    "window": WindowConfig;
    "devMode": boolean;
    "comfyUI": ComfyUIBackendConfig;
    "autocomplete": AutocompleteConfig;
    "generation": GenerationPanelConfig;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }
        if (!("window" in $$source)) {
            this["window"] = (new WindowConfig());
        }
        if (!("devMode" in $$source)) {
            this["devMode"] = false;
        }
        if (!("comfyUI" in $$source)) {
            this["comfyUI"] = (new ComfyUIBackendConfig());
        }
        if (!("autocomplete" in $$source)) {
            this["autocomplete"] = (new AutocompleteConfig());
        }
        if (!("generation" in $$source)) {
            this["generation"] = (new GenerationPanelConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField0_0($$parsedSource["folders"]);
        }
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField1_0($$parsedSource["tabs"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField2_0($$parsedSource["window"]);
        }
        if ("comfyUI" in $$parsedSource) {
            $$parsedSource["comfyUI"] = $$createField4_0($$parsedSource["comfyUI"]);
        }
        if ("autocomplete" in $$parsedSource) {
            $$parsedSource["autocomplete"] = $$createField5_0($$parsedSource["autocomplete"]);
        }
        if ("generation" in $$parsedSource) {
            $$parsedSource["generation"] = $$createField6_0($$parsedSource["generation"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class AutocompleteConfig {
    "enabled": boolean;
    "source": string;
    "suffix": string;
    "matchMode": string;
    "spacingMode": string;
    "sortMode": string;
    "whitespace": boolean;
    "escapeParens": boolean;
    "suggestionCap": number;

    /** Creates a new AutocompleteConfig instance. */
    constructor($$source: Partial<AutocompleteConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("suffix" in $$source)) {
            this["suffix"] = "";
        }
        if (!("matchMode" in $$source)) {
            this["matchMode"] = "";
        }
        if (!("spacingMode" in $$source)) {
            this["spacingMode"] = "";
        }
        if (!("sortMode" in $$source)) {
            this["sortMode"] = "";
        }
        if (!("whitespace" in $$source)) {
            this["whitespace"] = false;
        }
        if (!("escapeParens" in $$source)) {
            this["escapeParens"] = false;
        }
        if (!("suggestionCap" in $$source)) {
            this["suggestionCap"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutocompleteConfig($$parsedSource as Partial<AutocompleteConfig>);
    }
}

export class ComfyUIBackendConfig {
    "rootDir": string;
    "pythonPath": string;
    "mainScriptPath": string;
    "args": string;
    "outputDir": string;
    "modelPathsYAML": string;
    "host": string;
    "port": number;

    /** Creates a new ComfyUIBackendConfig instance. */
    constructor($$source: Partial<ComfyUIBackendConfig> = {}) {
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }
        if (!("pythonPath" in $$source)) {
            this["pythonPath"] = "";
        }
        if (!("mainScriptPath" in $$source)) {
            this["mainScriptPath"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("modelPathsYAML" in $$source)) {
            this["modelPathsYAML"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComfyUIBackendConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ComfyUIBackendConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComfyUIBackendConfig($$parsedSource as Partial<ComfyUIBackendConfig>);
    }
}

export class FolderConfig {
    "path": string;
    "scanMode": ScanMode;
    "alias": string;

    /** Creates a new FolderConfig instance. */
    constructor($$source: Partial<FolderConfig> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("scanMode" in $$source)) {
            this["scanMode"] = ScanMode.$zero;
        }
        if (!("alias" in $$source)) {
            this["alias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderConfig($$parsedSource as Partial<FolderConfig>);
    }
}

export class GenerationPanelConfig {
    "activeBackend": string;
    "mode": string;
    "txt2img": GenerationPanelTxt2Img;
    "img2img": GenerationPanelImg2Img;
    "history": GenerationPanelHistoryItem[];

    /** Creates a new GenerationPanelConfig instance. */
    constructor($$source: Partial<GenerationPanelConfig> = {}) {
        if (!("activeBackend" in $$source)) {
            this["activeBackend"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("txt2img" in $$source)) {
            this["txt2img"] = (new GenerationPanelTxt2Img());
        }
        if (!("img2img" in $$source)) {
            this["img2img"] = (new GenerationPanelImg2Img());
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationPanelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationPanelConfig {
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("txt2img" in $$parsedSource) {
            $$parsedSource["txt2img"] = $$createField2_0($$parsedSource["txt2img"]);
        }
        if ("img2img" in $$parsedSource) {
            $$parsedSource["img2img"] = $$createField3_0($$parsedSource["img2img"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField4_0($$parsedSource["history"]);
        }
        return new GenerationPanelConfig($$parsedSource as Partial<GenerationPanelConfig>);
    }
}

export class GenerationPanelHistoryItem {
    "id": string;
    "backend": string;
    "mode": string;
    "prompt": string;
    "createdAtISO": string;
    "resolution": GenerationPanelResolution;
    "steps": number;
    "cfgScale": number;
    "seed": string;

    /** Creates a new GenerationPanelHistoryItem instance. */
    constructor($$source: Partial<GenerationPanelHistoryItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("backend" in $$source)) {
            this["backend"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("createdAtISO" in $$source)) {
            this["createdAtISO"] = "";
        }
        if (!("resolution" in $$source)) {
            this["resolution"] = (new GenerationPanelResolution());
        }
        if (!("steps" in $$source)) {
            this["steps"] = 0;
        }
        if (!("cfgScale" in $$source)) {
            this["cfgScale"] = 0;
        }
        if (!("seed" in $$source)) {
            this["seed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationPanelHistoryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationPanelHistoryItem {
        const $$createField5_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resolution" in $$parsedSource) {
            $$parsedSource["resolution"] = $$createField5_0($$parsedSource["resolution"]);
        }
        return new GenerationPanelHistoryItem($$parsedSource as Partial<GenerationPanelHistoryItem>);
    }
}

export class GenerationPanelImg2Img {
    "prompt": string;
    "negativePrompt": string;
    "seed": string;
    "steps": number;
    "cfgScale": number;
    "resolution": GenerationPanelResolution;
    "model": string;
    "vae": string;
    "sampler": string;
    "scheduler": string;
    "sourceImagePath": string;
    "denoiseStrength": number;

    /** Creates a new GenerationPanelImg2Img instance. */
    constructor($$source: Partial<GenerationPanelImg2Img> = {}) {
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("negativePrompt" in $$source)) {
            this["negativePrompt"] = "";
        }
        if (!("seed" in $$source)) {
            this["seed"] = "";
        }
        if (!("steps" in $$source)) {
            this["steps"] = 0;
        }
        if (!("cfgScale" in $$source)) {
            this["cfgScale"] = 0;
        }
        if (!("resolution" in $$source)) {
            this["resolution"] = (new GenerationPanelResolution());
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("vae" in $$source)) {
            this["vae"] = "";
        }
        if (!("sampler" in $$source)) {
            this["sampler"] = "";
        }
        if (!("scheduler" in $$source)) {
            this["scheduler"] = "";
        }
        if (!("sourceImagePath" in $$source)) {
            this["sourceImagePath"] = "";
        }
        if (!("denoiseStrength" in $$source)) {
            this["denoiseStrength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationPanelImg2Img instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationPanelImg2Img {
        const $$createField5_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resolution" in $$parsedSource) {
            $$parsedSource["resolution"] = $$createField5_0($$parsedSource["resolution"]);
        }
        return new GenerationPanelImg2Img($$parsedSource as Partial<GenerationPanelImg2Img>);
    }
}

export class GenerationPanelResolution {
    "width": number;
    "height": number;

    /** Creates a new GenerationPanelResolution instance. */
    constructor($$source: Partial<GenerationPanelResolution> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationPanelResolution instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationPanelResolution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerationPanelResolution($$parsedSource as Partial<GenerationPanelResolution>);
    }
}

export class GenerationPanelTxt2Img {
    "prompt": string;
    "negativePrompt": string;
    "seed": string;
    "steps": number;
    "cfgScale": number;
    "resolution": GenerationPanelResolution;
    "model": string;
    "vae": string;
    "sampler": string;
    "scheduler": string;

    /** Creates a new GenerationPanelTxt2Img instance. */
    constructor($$source: Partial<GenerationPanelTxt2Img> = {}) {
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("negativePrompt" in $$source)) {
            this["negativePrompt"] = "";
        }
        if (!("seed" in $$source)) {
            this["seed"] = "";
        }
        if (!("steps" in $$source)) {
            this["steps"] = 0;
        }
        if (!("cfgScale" in $$source)) {
            this["cfgScale"] = 0;
        }
        if (!("resolution" in $$source)) {
            this["resolution"] = (new GenerationPanelResolution());
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("vae" in $$source)) {
            this["vae"] = "";
        }
        if (!("sampler" in $$source)) {
            this["sampler"] = "";
        }
        if (!("scheduler" in $$source)) {
            this["scheduler"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationPanelTxt2Img instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationPanelTxt2Img {
        const $$createField5_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resolution" in $$parsedSource) {
            $$parsedSource["resolution"] = $$createField5_0($$parsedSource["resolution"]);
        }
        return new GenerationPanelTxt2Img($$parsedSource as Partial<GenerationPanelTxt2Img>);
    }
}

export enum ScanMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ScanModeNormal = "normal",
    ScanModeWalk = "walk",
};

export class TabConfig {
    "id": string;
    "label": string;

    /**
     * empty means all
     */
    "path": string;
    "isWalk": boolean;

    /** Creates a new TabConfig instance. */
    constructor($$source: Partial<TabConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isWalk" in $$source)) {
            this["isWalk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TabConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabConfig($$parsedSource as Partial<TabConfig>);
    }
}

export class WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new WindowBounds instance. */
    constructor($$source: Partial<WindowBounds> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowBounds instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowBounds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowBounds($$parsedSource as Partial<WindowBounds>);
    }
}

export class WindowConfig {
    "state": string;
    "bounds": WindowBounds;
    "hasBounds": boolean;
    "normalBounds": WindowBounds;
    "hasNormalBounds": boolean;

    /** Creates a new WindowConfig instance. */
    constructor($$source: Partial<WindowConfig> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("bounds" in $$source)) {
            this["bounds"] = (new WindowBounds());
        }
        if (!("hasBounds" in $$source)) {
            this["hasBounds"] = false;
        }
        if (!("normalBounds" in $$source)) {
            this["normalBounds"] = (new WindowBounds());
        }
        if (!("hasNormalBounds" in $$source)) {
            this["hasNormalBounds"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowConfig {
        const $$createField1_0 = $$createType13;
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField1_0($$parsedSource["bounds"]);
        }
        if ("normalBounds" in $$parsedSource) {
            $$parsedSource["normalBounds"] = $$createField3_0($$parsedSource["normalBounds"]);
        }
        return new WindowConfig($$parsedSource as Partial<WindowConfig>);
    }
}

// Private type creation functions
const $$createType0 = FolderConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TabConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = WindowConfig.createFrom;
const $$createType5 = ComfyUIBackendConfig.createFrom;
const $$createType6 = AutocompleteConfig.createFrom;
const $$createType7 = GenerationPanelConfig.createFrom;
const $$createType8 = GenerationPanelTxt2Img.createFrom;
const $$createType9 = GenerationPanelImg2Img.createFrom;
const $$createType10 = GenerationPanelHistoryItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = GenerationPanelResolution.createFrom;
const $$createType13 = WindowBounds.createFrom;
