// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class ImageRecord {
    "ID": number;
    "Path": string;
    "Hash": string;
    "FileSize": number;
    "ModifiedUnixNs": number;
    "Prompt": string;
    "NegativePrompt": string;
    "Model": string;
    "Sampler": string;
    "Seed": string;
    "CfgScale": number;
    "Width": number;
    "Height": number;
    "AddedAt": time$0.Time;

    /** Creates a new ImageRecord instance. */
    constructor($$source: Partial<ImageRecord> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("FileSize" in $$source)) {
            this["FileSize"] = 0;
        }
        if (!("ModifiedUnixNs" in $$source)) {
            this["ModifiedUnixNs"] = 0;
        }
        if (!("Prompt" in $$source)) {
            this["Prompt"] = "";
        }
        if (!("NegativePrompt" in $$source)) {
            this["NegativePrompt"] = "";
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Sampler" in $$source)) {
            this["Sampler"] = "";
        }
        if (!("Seed" in $$source)) {
            this["Seed"] = "";
        }
        if (!("CfgScale" in $$source)) {
            this["CfgScale"] = 0;
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("AddedAt" in $$source)) {
            this["AddedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageRecord($$parsedSource as Partial<ImageRecord>);
    }
}
