// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1860977610);
}

export function GetComfyUIConfig(): $CancellablePromise<config$0.ComfyUIBackendConfig> {
    return $Call.ByID(1996817148).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetSetupStatus(): $CancellablePromise<$models.ComfyUISetupStatus> {
    return $Call.ByID(4201319279).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStatus(): $CancellablePromise<$models.ComfyUIStatus> {
    return $Call.ByID(1471840282).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InstallComfyUI(): $CancellablePromise<void> {
    return $Call.ByID(1585105211);
}

export function ListLogs(limit: number): $CancellablePromise<$models.ComfyUILogEntry[]> {
    return $Call.ByID(1794459087, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(4133160727);
}

export function SetComfyUIConfig(next: config$0.ComfyUIBackendConfig): $CancellablePromise<config$0.ComfyUIBackendConfig> {
    return $Call.ByID(4255080112, next).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1314053728);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3484358308);
}

// Private type creation functions
const $$createType0 = config$0.ComfyUIBackendConfig.createFrom;
const $$createType1 = $models.ComfyUISetupStatus.createFrom;
const $$createType2 = $models.ComfyUIStatus.createFrom;
const $$createType3 = $models.ComfyUILogEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
