// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFolder adds a new supervised folder and triggers a scan.
 */
export function AddFolder(path: string, mode: config$0.ScanMode): $CancellablePromise<void> {
    return $Call.ByID(255073735, path, mode);
}

/**
 * ClearIndexAndReindex clears indexed image data and thumbnail cache, then starts a fresh scan.
 */
export function ClearIndexAndReindex(): $CancellablePromise<void> {
    return $Call.ByID(1114111755);
}

/**
 * GetConfig returns the application configuration.
 */
export function GetConfig(): $CancellablePromise<config$0.AppConfig> {
    return $Call.ByID(1693510026).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetImages returns a paginated list of images, optionally matching a search query and filtered by folder.
 */
export function GetImages(query: string, folderPath: string, offset: number, limit: number): $CancellablePromise<$models.PaginatedImages | null> {
    return $Call.ByID(3312439230, query, folderPath, offset, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenExternally opens a file using the default OS application
 */
export function OpenExternally(path: string): $CancellablePromise<void> {
    return $Call.ByID(2481728976, path);
}

/**
 * RemoveFolder removes a supervised folder and purges indexed images immediately.
 */
export function RemoveFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3664983788, path);
}

/**
 * SetTabs updates the tabs configuration.
 */
export function SetTabs(tabs: config$0.TabConfig[]): $CancellablePromise<void> {
    return $Call.ByID(1347256724, tabs);
}

/**
 * ShowInFolder opens the file explorer and selects the file
 */
export function ShowInFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3474754050, path);
}

/**
 * UpdateFolderAlias updates the alias for a supervised folder.
 */
export function UpdateFolderAlias(path: string, alias: string): $CancellablePromise<void> {
    return $Call.ByID(3730665955, path, alias);
}

// Private type creation functions
const $$createType0 = config$0.AppConfig.createFrom;
const $$createType1 = $models.PaginatedImages.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
