// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAutocompleteSources(): $CancellablePromise<string[]> {
    return $Call.ByID(2803367964).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAutocompleteSuggestions(query: $models.AutocompleteQuery): $CancellablePromise<$models.AutocompleteSuggestion[]> {
    return $Call.ByID(1012996511, query).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetModelCatalog(): $CancellablePromise<$models.GenerationModelCatalog | null> {
    return $Call.ByID(483824322).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.AutocompleteSuggestion.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.GenerationModelCatalog.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
