// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export class PaginatedImages {
    "images": db$0.ImageRecord[];
    "totalCount": number;
    "offset": number;
    "limit": number;

    /** Creates a new PaginatedImages instance. */
    constructor($$source: Partial<PaginatedImages> = {}) {
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginatedImages instance from a string or object.
     */
    static createFrom($$source: any = {}): PaginatedImages {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField0_0($$parsedSource["images"]);
        }
        return new PaginatedImages($$parsedSource as Partial<PaginatedImages>);
    }
}

// Private type creation functions
const $$createType0 = db$0.ImageRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
