// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export class AutocompleteQuery {
    "input": string;
    "limit": number;

    /** Creates a new AutocompleteQuery instance. */
    constructor($$source: Partial<AutocompleteQuery> = {}) {
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutocompleteQuery($$parsedSource as Partial<AutocompleteQuery>);
    }
}

export class AutocompleteSuggestion {
    "tag": string;
    "category": number;
    "popularity": number;
    "alternative": string;
    "insertText": string;
    "matchedBy": string;
    "matchedValue": string;

    /** Creates a new AutocompleteSuggestion instance. */
    constructor($$source: Partial<AutocompleteSuggestion> = {}) {
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = 0;
        }
        if (!("popularity" in $$source)) {
            this["popularity"] = 0;
        }
        if (!("alternative" in $$source)) {
            this["alternative"] = "";
        }
        if (!("insertText" in $$source)) {
            this["insertText"] = "";
        }
        if (!("matchedBy" in $$source)) {
            this["matchedBy"] = "";
        }
        if (!("matchedValue" in $$source)) {
            this["matchedValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteSuggestion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutocompleteSuggestion($$parsedSource as Partial<AutocompleteSuggestion>);
    }
}

export class ComfyUILogEntry {
    "timestamp": string;
    "level": string;
    "stream": string;
    "message": string;

    /** Creates a new ComfyUILogEntry instance. */
    constructor($$source: Partial<ComfyUILogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("stream" in $$source)) {
            this["stream"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComfyUILogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ComfyUILogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComfyUILogEntry($$parsedSource as Partial<ComfyUILogEntry>);
    }
}

export class ComfyUIStatus {
    "state": string;
    "running": boolean;
    "pid": number;
    "host": string;
    "port": number;
    "startedAt": string;
    "lastError": string;
    "statusMessage": string;
    "managedExternally": boolean;

    /** Creates a new ComfyUIStatus instance. */
    constructor($$source: Partial<ComfyUIStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("statusMessage" in $$source)) {
            this["statusMessage"] = "";
        }
        if (!("managedExternally" in $$source)) {
            this["managedExternally"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComfyUIStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ComfyUIStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComfyUIStatus($$parsedSource as Partial<ComfyUIStatus>);
    }
}

export class FolderBrowseResponse {
    "rootPath": string;
    "currentPath": string;
    "parentPath": string;
    "folders": FolderEntry[];
    "images": db$0.ImageRecord[];
    "totalCount": number;
    "offset": number;
    "limit": number;

    /** Creates a new FolderBrowseResponse instance. */
    constructor($$source: Partial<FolderBrowseResponse> = {}) {
        if (!("rootPath" in $$source)) {
            this["rootPath"] = "";
        }
        if (!("currentPath" in $$source)) {
            this["currentPath"] = "";
        }
        if (!("parentPath" in $$source)) {
            this["parentPath"] = "";
        }
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderBrowseResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderBrowseResponse {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField3_0($$parsedSource["folders"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField4_0($$parsedSource["images"]);
        }
        return new FolderBrowseResponse($$parsedSource as Partial<FolderBrowseResponse>);
    }
}

export class FolderEntry {
    "name": string;
    "path": string;

    /** Creates a new FolderEntry instance. */
    constructor($$source: Partial<FolderEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderEntry($$parsedSource as Partial<FolderEntry>);
    }
}

export class GenerationModelCatalog {
    "samplers": string[];
    "schedulers": string[];
    "checkpoints": string[];
    "vaes": string[];
    "loras": string[];
    "controlnets": string[];
    "upscaleModels": string[];
    "textEncoders": string[];
    "diffusionModels": string[];
    "unets": string[];

    /** Creates a new GenerationModelCatalog instance. */
    constructor($$source: Partial<GenerationModelCatalog> = {}) {
        if (!("samplers" in $$source)) {
            this["samplers"] = [];
        }
        if (!("schedulers" in $$source)) {
            this["schedulers"] = [];
        }
        if (!("checkpoints" in $$source)) {
            this["checkpoints"] = [];
        }
        if (!("vaes" in $$source)) {
            this["vaes"] = [];
        }
        if (!("loras" in $$source)) {
            this["loras"] = [];
        }
        if (!("controlnets" in $$source)) {
            this["controlnets"] = [];
        }
        if (!("upscaleModels" in $$source)) {
            this["upscaleModels"] = [];
        }
        if (!("textEncoders" in $$source)) {
            this["textEncoders"] = [];
        }
        if (!("diffusionModels" in $$source)) {
            this["diffusionModels"] = [];
        }
        if (!("unets" in $$source)) {
            this["unets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationModelCatalog instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationModelCatalog {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("samplers" in $$parsedSource) {
            $$parsedSource["samplers"] = $$createField0_0($$parsedSource["samplers"]);
        }
        if ("schedulers" in $$parsedSource) {
            $$parsedSource["schedulers"] = $$createField1_0($$parsedSource["schedulers"]);
        }
        if ("checkpoints" in $$parsedSource) {
            $$parsedSource["checkpoints"] = $$createField2_0($$parsedSource["checkpoints"]);
        }
        if ("vaes" in $$parsedSource) {
            $$parsedSource["vaes"] = $$createField3_0($$parsedSource["vaes"]);
        }
        if ("loras" in $$parsedSource) {
            $$parsedSource["loras"] = $$createField4_0($$parsedSource["loras"]);
        }
        if ("controlnets" in $$parsedSource) {
            $$parsedSource["controlnets"] = $$createField5_0($$parsedSource["controlnets"]);
        }
        if ("upscaleModels" in $$parsedSource) {
            $$parsedSource["upscaleModels"] = $$createField6_0($$parsedSource["upscaleModels"]);
        }
        if ("textEncoders" in $$parsedSource) {
            $$parsedSource["textEncoders"] = $$createField7_0($$parsedSource["textEncoders"]);
        }
        if ("diffusionModels" in $$parsedSource) {
            $$parsedSource["diffusionModels"] = $$createField8_0($$parsedSource["diffusionModels"]);
        }
        if ("unets" in $$parsedSource) {
            $$parsedSource["unets"] = $$createField9_0($$parsedSource["unets"]);
        }
        return new GenerationModelCatalog($$parsedSource as Partial<GenerationModelCatalog>);
    }
}

export class GenerationQueueJob {
    "jobId": string;
    "mode": string;
    "prompt": string;
    "state": string;
    "queuedAt": string;
    "startedAt": string;
    "finishedAt": string;
    "error": string;
    "promptId": string;

    /** Creates a new GenerationQueueJob instance. */
    constructor($$source: Partial<GenerationQueueJob> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("queuedAt" in $$source)) {
            this["queuedAt"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("promptId" in $$source)) {
            this["promptId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationQueueJob instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationQueueJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerationQueueJob($$parsedSource as Partial<GenerationQueueJob>);
    }
}

export class GenerationRequest {
    "requestId": string;
    "mode": string;
    "prompt": string;
    "negativePrompt": string;
    "seed": string;
    "steps": number;
    "cfgScale": number;
    "width": number;
    "height": number;
    "model": string;
    "vae": string;
    "sampler": string;
    "scheduler": string;

    /** Creates a new GenerationRequest instance. */
    constructor($$source: Partial<GenerationRequest> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("negativePrompt" in $$source)) {
            this["negativePrompt"] = "";
        }
        if (!("seed" in $$source)) {
            this["seed"] = "";
        }
        if (!("steps" in $$source)) {
            this["steps"] = 0;
        }
        if (!("cfgScale" in $$source)) {
            this["cfgScale"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("vae" in $$source)) {
            this["vae"] = "";
        }
        if (!("sampler" in $$source)) {
            this["sampler"] = "";
        }
        if (!("scheduler" in $$source)) {
            this["scheduler"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerationRequest($$parsedSource as Partial<GenerationRequest>);
    }
}

export class GenerationResult {
    "promptId": string;
    "mode": string;
    "imagePath": string;
    "outputDir": string;
    "seed": string;
    "startedAt": string;
    "completedAt": string;

    /** Creates a new GenerationResult instance. */
    constructor($$source: Partial<GenerationResult> = {}) {
        if (!("promptId" in $$source)) {
            this["promptId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("imagePath" in $$source)) {
            this["imagePath"] = "";
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("seed" in $$source)) {
            this["seed"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerationResult($$parsedSource as Partial<GenerationResult>);
    }
}

export class PaginatedImages {
    "images": db$0.ImageRecord[];
    "totalCount": number;
    "offset": number;
    "limit": number;

    /** Creates a new PaginatedImages instance. */
    constructor($$source: Partial<PaginatedImages> = {}) {
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginatedImages instance from a string or object.
     */
    static createFrom($$source: any = {}): PaginatedImages {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField0_0($$parsedSource["images"]);
        }
        return new PaginatedImages($$parsedSource as Partial<PaginatedImages>);
    }
}

export class ParserPluginInfo {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "main": string;
    "priority": number;
    "folderPath": string;
    "status": string;
    "trusted": boolean;
    "enabled": boolean;
    "error": string;

    /** Creates a new ParserPluginInfo instance. */
    constructor($$source: Partial<ParserPluginInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("main" in $$source)) {
            this["main"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("folderPath" in $$source)) {
            this["folderPath"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("trusted" in $$source)) {
            this["trusted"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParserPluginInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ParserPluginInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParserPluginInfo($$parsedSource as Partial<ParserPluginInfo>);
    }
}

export class ParserPluginLogEntry {
    "timestamp": string;
    "pluginID": string;
    "level": string;
    "message": string;

    /** Creates a new ParserPluginLogEntry instance. */
    constructor($$source: Partial<ParserPluginLogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("pluginID" in $$source)) {
            this["pluginID"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParserPluginLogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ParserPluginLogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParserPluginLogEntry($$parsedSource as Partial<ParserPluginLogEntry>);
    }
}

export class QueueGenerationResponse {
    "jobId": string;
    "position": number;
    "state": string;

    /** Creates a new QueueGenerationResponse instance. */
    constructor($$source: Partial<QueueGenerationResponse> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueGenerationResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueGenerationResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueGenerationResponse($$parsedSource as Partial<QueueGenerationResponse>);
    }
}

// Private type creation functions
const $$createType0 = FolderEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.ImageRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
